### ISSUE TITLE
Not working on Deluge 1.3.15

### ISSUE THREAD

**Issue by somedude305** [stefantalpalaru/deluge-default-trackers#32]
When I enable it then reopen the settings it will untick itself. Also I have no idea how I'm supposed to add a url to sync the trackers. If you could help with both these issues it'd be appreciated.

OS: Windows 10

**Comment by stefantalpalaru** [comment]
Try updating your Deluge version. The latest is 2.0.3.

See also the instructions for getting debugging output: https://github.com/stefantalpalaru/deluge-default-trackers#troubleshooting

**Comment by CoolSpot** [comment]
@somedude305 , installing this egg - https://github.com/stefantalpalaru/deluge-default-trackers/raw/Deluge-1.3/egg/DefaultTrackers-0.1-py2.7.egg as suggested in #29 helped me because it doesn't require the python package "six".
Also if you have a newer version (0.2) of the plugin already installed, you must delete it from the folder C:\Users\YOUR_USER_NAME\AppData\Roaming\deluge\plugins and do "Rescan Plugins" to activate the version 0.1 .
